# Generated by Django 3.2.5 on 2021-07-18 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_shows_app', '0002_remove_show_descirption'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='descirption',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
